version: '3.4'

services:                          

  package-installer:
    image: client-side-dev-env
    volumes:
      - ./:/home/app
    entrypoint: yarn install
    deploy:
      restart_policy:
        condition: on-failure
        
  client-side-dev-env:
    image: client-side-dev-env
    volumes:
      - ./:/home/app
    ports:
      - "7000:4200"